"""secondary table

Revision ID: 3cf4d59ddfbd
Revises: 07fa739614e0
Create Date: 2025-09-21 20:57:47.308252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf4d59ddfbd'
down_revision = '07fa739614e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('Option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_options')
    # ### end Alembic commands ###
