"""delete column of products_id from Options

Revision ID: 4c2e3e2b8f39
Revises: 3cf4d59ddfbd
Create Date: 2025-09-21 22:04:25.873559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2e3e2b8f39'
down_revision = '3cf4d59ddfbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('options_products_id_fkey'), type_='foreignkey')
        batch_op.drop_column('products_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('options_products_id_fkey'), 'products', ['products_id'], ['id'])

    # ### end Alembic commands ###
