"""add column(deleted, provided) to OrderItems

Revision ID: 78412e789323
Revises: 2d38a6c70f07
Create Date: 2025-10-23 10:49:02.844092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78412e789323'
down_revision = '2d38a6c70f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('provided', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('provided')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
