"""orderlist add options

Revision ID: 7dc107a289e2
Revises: e6666235fa16
Create Date: 2025-09-26 10:56:34.876596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc107a289e2'
down_revision = 'e6666235fa16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'options', ['options_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('options_id')

    # ### end Alembic commands ###
