"""Option_id 2 option_id from product_options

Revision ID: dd202e846160
Revises: 4c2e3e2b8f39
Create Date: 2025-09-21 22:08:21.216244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd202e846160'
down_revision = '4c2e3e2b8f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('product_options_Option_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'options', ['option_id'], ['id'])
        batch_op.drop_column('Option_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Option_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_options_Option_id_fkey'), 'options', ['Option_id'], ['id'])
        batch_op.drop_column('option_id')

    # ### end Alembic commands ###
