"""create intermedia tabel; OrderItems/Options

Revision ID: debbdd26bc3c
Revises: 7dc107a289e2
Create Date: 2025-09-26 11:32:29.395087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debbdd26bc3c'
down_revision = '7dc107a289e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordered_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_options_id_fkey'), type_='foreignkey')
        batch_op.drop_column('options_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('order_items_options_id_fkey'), 'options', ['options_id'], ['id'])

    op.drop_table('ordered_options')
    # ### end Alembic commands ###
